{% set version = '0.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-webshot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/webshot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/webshot/webshot_{{ version }}.tar.gz
  sha256: f0a1be8b0563d95550569a0620d546a9876d1e279a932e9293e4be57ff0f271f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: httpuv, knitr, rmarkdown, shiny
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-jsonlite
    - r-magrittr
    - r-processx
    - r-withr

  run:
    - r-base
    - r-jsonlite
    - r-magrittr
    - r-processx
    - r-withr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('webshot')"           # [not win]
    - "\"%R%\" -e \"library('webshot')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/wch/webshot/
  license: GPL-2
  summary: Takes screenshots of web pages, including Shiny applications and R Markdown documents.
  license_family: GPL2

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: webshot
# Title: Take Screenshots of Web Pages
# Version: 0.5.0
# Authors@R: c( person("Winston", "Chang", email = "winston@rstudio.com", role = c("aut", "cre")), person("Yihui", "Xie", role = "ctb"), person("Francois", "Guillem", role = "ctb"), person("Nicolas", "Perriault", role = "ctb", comment = "The CasperJS library") )
# Description: Takes screenshots of web pages, including Shiny applications and R Markdown documents.
# Depends: R (>= 3.0)
# Imports: magrittr, jsonlite, withr, processx
# Suggests: httpuv, knitr, rmarkdown, shiny
# VignetteBuilder: knitr
# License: GPL-2
# SystemRequirements: PhantomJS (http://phantomjs.org) for taking screenshots, ImageMagick (http://www.imagemagick.org) or GraphicsMagick (http://www.graphicsmagick.org) and OptiPNG (http://optipng.sourceforge.net) for manipulating images.
# RoxygenNote: 6.0.1.9000
# URL: https://github.com/wch/webshot/
# NeedsCompilation: no
# Packaged: 2017-11-29 18:23:26 UTC; winston
# Author: Winston Chang [aut, cre], Yihui Xie [ctb], Francois Guillem [ctb], Nicolas Perriault [ctb] (The CasperJS library)
# Maintainer: Winston Chang <winston@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-11-29 18:55:45 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
