travis:
  secure:
    BINSTAR_TOKEN: F9z4SLqNxDeCuYwpRoiuY50SHsNniHZdUietW7NxzzxfbyizGW+RbmKIJARhM6UlxmwrxYimYSPBcURIKCYoWzsl1pga4jOIRyXpi5gdEZUfTUtpFrRLOcpjSKA7LcIKH1DrfOLiH1YOFUv/g/lab9Eqhym1+7h8fEqRxF5uF5lNa1xgDHfzIR15iWOL0CrPe/9ChEPsjnEfHvMa2gUI6RIElMmSgNDxC3oSp+sQtMMUWLB8+54fKf9sFjg0weSjF3jbOkJoJurMkH5GFLperqxAKdr9TcB7WVdAM/OUowV+ffOjdPP4mHv71ghaa5fOBZRHaRZmAjTWkCJmWjxZiqR0/LvtdzcVu8WE9cXNkBosJlkIjASO8CvA3aju2l0RXh8TiY9xhjb7kPLnpD/Qa5h9GiKDF1zzkKBNubGJ1R9+nNBJtZCAzB7es1t++9/523jlWaku2JEwV0gVN1NYtrYlMRCkYJrJqzenQDggAPzDKmRT56zB34Ee21Kg/S5eKPZa2P1AK7vC7QIXa2wzzdN2E1JMRxGVPCTOg6eWOoRzt962Sk5TsbqQOzFGR+C0Ac0d9bT1hfkDX09OybkOelnaHHr9x7M/p1w13/fMsQDCvz0azp2WqQb8CZkYrh5XikNWXGGSMZTSyD/ZCN/Bq03v3B1Tv1G0T+Ux28hqs48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
